version: 2
jobs:
  # To test, we just build the code, run the tests, then create and upload
  # a coverage report.
  test:
    docker:
      - image: node:9
    steps:
      - checkout
      - run: make test
      - run: cd aac-cli; npm run cov
      - run: cd aac-cli; bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build:
    jobs:
      - test:
          # All branches, all tags.
          filters:
            tags:
              only: /.*/
